package com.sovchilar.made.uitls

const val maleGender = "male"
const val femaleGender = "female"
const val marriageDivorced = "divorced"
const val noMarriage = "noMarriage"
const val tashkent = "Tashkent"
const val tashkent_region = "Tashkent region"
const val karakalpak_region = "Karakalpakstan"
const val andijan_region = "Andijan region"
const val bukhara_region = "Bukhara region"
const val djizzak_region = "Jizzakh region"
const val fergana_region = "Fergana region"
const val kashkadarya_region = "Qashqadaryo region"
const val horezm_region = "Xorazm region"
const val namangan_region = "Namangan region"
const val novoi_region = "Navoiy region"
const val samarkand_region = "Samarqand region"
const val surxandarya_region = "Surxondaryo region"
const val sirdarya_region = "Sirdaryo region"
const val uzbekistan = "Uzbekistan"